# Primer array

> Primeros pasos como Data Science



In [1]:
import numpy as np # 'np' es el alias universal — úsalo siempre así


In [3]:
# Crear un array desde una lista
precios = np.array([10.5, 23.0 , 8.75, 45.2, 12.0])

print("Array:" , precios)
print("Tipo:", type(precios)) # numpy.ndarray
print("Tpo de dato: ", precios.dtype)# float64
print("forma:", precios.shape)# (5,) → 5 elementos, 1 dimensión
print("dimensiones:", precios.ndim) # 1

Array: [10.5  23.    8.75 45.2  12.  ]
Tipo: <class 'numpy.ndarray'>
Tpo de dato:  float64
forma: (5,)
dimensiones: 1


Demostración de velocidad


In [6]:
import time


In [12]:
N = 1_000_000
# Con lista Python — necesita un bucle
lista = list(range(N))
t0 = time.time()
r1 = [x * 2 for x in lista]
print(f"Lista Python: {(time.time()-t0)*1000:.1f} ms")

# Con Numpy — sin bucle
arr = np.arange(N)
t0 = time.time()
r2 = arr * 2
print(f"Numpy: {(time.time()-t0)*1000:.1f} ms")

Lista Python: 32.0 ms
Numpy: 0.8 ms


Operaciones Aritméticas — El Concepto Universal

In [13]:
a = np.array([1,2,3,4,5])
b = np.array([10, 20, 30, 40, 50])

print("Suma:",     a + b)    # [11 22 33 44 55]
print("Producto:", a * b)    # [ 10  40  90 160 250]
print("Cuadrado:", a ** 2)  # [ 1  4  9 16 25]
print("Módulo %2:", a % 2)   # [1 0 1 0 1] → 1=impar, 0=par
print("Módulo %5:", a % 5)   # [1 2 3 4 0] → 0=múltiplo de 5

# Escalar: se aplica a todos (broadcasting)
print("IVA 19%:", b * 1.19)  # [11.9  23.8  35.7  47.6  59.5]

Suma: [11 22 33 44 55]
Producto: [ 10  40  90 160 250]
Cuadrado: [ 1  4  9 16 25]
Módulo %2: [1 0 1 0 1]
Módulo %5: [1 2 3 4 0]
IVA 19%: [11.9 23.8 35.7 47.6 59.5]


Funciones de Agregación

In [14]:
ventas = np.array([1200, 850, 2100, 750, 1900, 1100, 650])

print("Suma:         ", np.sum(ventas))      # 8550
print("Promedio:     ", np.mean(ventas))     # 1221.43
print("Mediana:      ", np.median(ventas))   # 1100.0
print("Máximo:       ", np.max(ventas))      # 2100
print("Mínimo:       ", np.min(ventas))      # 650
print("Desv. std:    ", np.std(ventas))      # 509.48
print("Posición max: ", np.argmax(ventas))   # 2 → índice del mayor
print("Ordenado:     ", np.sort(ventas))     # [650 750 850 ...]

Suma:          8550
Promedio:      1221.4285714285713
Mediana:       1100.0
Máximo:        2100
Mínimo:        650
Desv. std:     525.6676997992599
Posición max:  2
Ordenado:      [ 650  750  850 1100 1200 1900 2100]


Slicing — Seleccionar Rangos

In [16]:
t = np.array([28, 31, 25, 33, 35, 29, 27])
#             0    1   2   3   4   5    6

print(t[0]) # 28  → primer elemento
print(t[-1])# 27  → último
print(t[0:3])# [28 31 25] → índices 0,1,2 (el 3 NO se incluye)
print(t[2::]) # [25 33 35 29 27] → desde índice 2 hasta el final
print(t[::2])# [28 25 35 27] → cada 2 pasos
print(t[::-1])# [27 29 35 33 25 31 28] → invertido
print(t[[0,2,4]])# [28 25 35] → índices múltiples (solo Numpy)

28
27
[28 31 25]
[25 33 35 29 27]
[28 25 35 27]
[27 29 35 33 25 31 28]
[28 25 35]


Boolean Indexing — Filtrado Poderoso

In [18]:
edades = np.array([18, 22, 15, 35, 28, 14, 40])

# La condición crea un array de True/False
print(edades >= 18 ) # [ True  True False  True  True False  True]

# Usas ese array como índice → solo retorna los True
print(edades[edades >= 18]) # [18 22 35 28 40]


# Combinar condiciones con & (AND) y | (OR)
# SIEMPRE pon cada condición entre paréntesis
jovenes = edades[(edades >= 18) & (edades <= 25)]
print(jovenes)# [18 22]

# Contar cuántos cumplen la condición
print(np.sum(edades >= 18)) #5
print(np.mean(edades >= 18) * 100, "%")  # 71.4 % son mayores de edad



[ True  True False  True  True False  True]
[18 22 35 28 40]
[18 22]
5
71.42857142857143 %


Arrays 2D — Matrices

In [19]:
# Matriz 4x3: 4 pacientes, 3 medidas (peso kg, altura cm, temp °C)
M = np.array([
    [70, 175, 36.8],
    [85, 180, 37.2],
    [60, 165, 38.5], # ← fiebre!
    [92, 178, 36.5]
     ])
print("Forma:", M.shape)           # (4, 3)
print(M[0]) # [70. 175. 36.8] → fila 0
print(M[2,2]) # 38.5 → fila 2, columna 2
print(M[:,2])# [36.8 37.2 38.5 36.5] → temp de todos

# axis=0 → promedio de cada columna (un valor por columna)
print(np.mean(M, axis=0))  # [76.75 174.5  37.25]

# Detectar pacientes con fiebre
temps = M[:,2]
print("Con fiebre:", np.where(temps > 38))  # (array([2]),)


Forma: (4, 3)
[ 70.  175.   36.8]
38.5
[36.8 37.2 38.5 36.5]
[ 76.75 174.5   37.25]
Con fiebre: (array([2]),)


Ejercicios del Capítulo


Análisis de Temperaturas Semanales
Tienes las temperaturas máximas de 14 días: [28,31,25,33,35,29,27,32,36,34,28,30,22,26]

Calcula promedio, máxima, mínima y desviación estándar.
¿Cuántos días superaron 30°C? ¿Qué porcentaje representan?
Obtén las temperaturas de la segunda semana (días 7 al 13).
Calcula el promedio de cada semana por separado y di cuál fue más caliente.

In [22]:
temp = np.array([28,31,25,33,35,29,27,32,36,34,28,30,22,26])

# Estadísticas
print(f"Promedio: {np.mean(temps):.1f}°C")    # 30.4°C
print(f"Máxima: {np.max(temps)}°C")           # 36°C
print(f"Mínima: {np.min(temps)}°C")           # 22°C
print(f"Desv std: {np.std(temps):.1f}°C")    # 3.9°C

# Días sobre 30°C
sobre30 = np.sum(temps > 30)
print(f"Días > 30°C: {sobre30} ({sobre30/len(temps)*100:.0f}%)")
# 6 días (43%)

# Segunda semana: índices 7 al 13 inclusive
s2 = temps[7:14]
print("Segunda semana:", s2)  # [32 36 34 28 30 22 26]

# Promedio por semana
p1 = np.mean(temps[:7])
p2 = np.mean(temps[7:])
print(f"Semana 1: {p1:.1f}°C | Semana 2: {p2:.1f}°C")
# Semana 1: 29.7°C | Semana 2: 29.7°C  → ¡empate!
print("Más caliente:", "Semana 1" if p1 > p2 else "Semana 2" if p2 > p1 else "Empate")

Promedio: 37.2°C
Máxima: 38.5°C
Mínima: 36.5°C
Desv std: 0.8°C
Días > 30°C: 4 (100%)
Segunda semana: []
Semana 1: 37.2°C | Semana 2: nan°C
Más caliente: Empate


Filtrado Numérico con Módulo
Dado el array np.arange(1, 101) (números del 1 al 100):

Encuentra todos los múltiplos de 7.
Encuentra los múltiplos de 3 Y de 5 a la vez (múltiplos de 15).
Encuentra los números impares mayores de 50.
Calcula la suma de todos los números pares del 1 al 100. (Respuesta esperada: 2550)

In [24]:
nums = np.arange(1, 101)

# Múltiplos de 7: residuo al dividir por 7 es 0
print("Múlt. de 7:", nums[nums % 7 == 0])
# [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]

# Múltiplos de 3 Y de 5 → múltiplos de 15
m15 = nums[(nums % 3 == 0) & (nums % 5 == 0)]
print("Múlt. de 15:", m15)  # [15 30 45 60 75 90]

# Impares (residuo %2 == 1) y mayores de 50
imp50 = nums[(nums % 2 == 1) & (nums > 50)]
print("Impares > 50:", imp50)
# [51 53 55 ... 99]  → 25 números

# Suma de pares
print("Suma de pares:", np.sum(nums[nums % 2 == 0]))  # 2550

Múlt. de 7: [ 7 14 21 28 35 42 49 56 63 70 77 84 91 98]
Múlt. de 15: [15 30 45 60 75 90]
Impares > 50: [51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97
 99]
Suma de pares: 2550


Análisis de Ventas en Matriz 2D
Matriz de ventas: 4 vendedores × 3 meses. Datos: [[1200,1500,1100],[900,1800,2100],[1400,1200,1600],[800,950,1050]]

Total de ventas por mes (eje de columnas).
¿Qué vendedor tuvo el mejor promedio trimestral?
Normaliza las ventas de cada vendedor dividiéndolas por su máximo (resultado entre 0 y 1).
¿En qué mes se vendió más en total? ¿Y menos?

In [25]:
V = np.array([
    [1200,1500,1100],  # vendedor 0
    [ 900,1800,2100],  # vendedor 1
    [1400,1200,1600],  # vendedor 2
    [ 800, 950,1050]   # vendedor 3
])
meses = ['Enero','Febrero','Marzo']

# Total por mes: axis=0 suma las filas → resultado por columna
total_mes = np.sum(V, axis=0)
for m, t in zip(meses, total_mes):
    print(f"  {m}: ${t:,}")
# Enero: $4,300  Febrero: $5,450  Marzo: $5,850

# Mejor vendedor: promedio por fila (axis=1)
prom = np.mean(V, axis=1)
mejor = np.argmax(prom)
print(f"\nMejor vendedor: #{mejor} (promedio ${prom[mejor]:.0f})")
# Mejor: #1 (promedio $1600)

# Normalizar: dividir por el máximo de cada vendedor
# keepdims=True mantiene forma (4,1) para que el broadcast funcione
maxs = np.max(V, axis=1, keepdims=True)  # forma (4,1)
norm = V / maxs                              # broadcast: (4,3) / (4,1)
print("\nNormalizado:\n", np.round(norm, 2))

# Mejor y peor mes
print(f"\nMejor mes: {meses[np.argmax(total_mes)]}")   # Marzo
print(f"Peor mes:  {meses[np.argmin(total_mes)]}")   # Enero

  Enero: $4,300
  Febrero: $5,450
  Marzo: $5,850

Mejor vendedor: #1 (promedio $1600)

Normalizado:
 [[0.8  1.   0.73]
 [0.43 0.86 1.  ]
 [0.88 0.75 1.  ]
 [0.76 0.9  1.  ]]

Mejor mes: Marzo
Peor mes:  Enero
